const { Log } = require('./logger');

const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJnYWdhbi5zYWkyMDIyQHZpdHN0dWRlbnQuYWMuaW4iLCJleHAiOjE3Nzg5Mjg3ODksImlhdCI6MTc3ODkyNzg4OSwiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6IjI1MTIyODkyLTAwMjQtNDIwMS1iOWQ1LTllOWQxMmYzZmU1MyIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6ImNoZWxsYWJveWluYSBnYWdhbiBzYWkiLCJzdWIiOiI0NWQwYjliOC0zZGI5LTRlZGMtODlmZi01ZGQyODZkZmE0YzAifSwiZW1haWwiOiJnYWdhbi5zYWkyMDIyQHZpdHN0dWRlbnQuYWMuaW4iLCJuYW1lIjoiY2hlbGxhYm95aW5hIGdhZ2FuIHNhaSIsInJvbGxObyI6IjIybWlzMDM5NSIsImFjY2Vzc0NvZGUiOiJTZkZ1V2ciLCJjbGllbnRJRCI6IjQ1ZDBiOWI4LTNkYjktNGVkYy04OWZmLTVkZDI4NmRmYTRjMCIsImNsaWVudFNlY3JldCI6ImdUQWtla1FGVUVBUlpjdkcifQ.wWBL-Jd-EMcnK9L-lDkNWx7aV3KJyIhDYc8lDgyRSCc';

Log(
  'backend',
  'error',
  'handler',
  'received string, expected bool',
  token
);
